### ISSUE TITLE
add order-zeebe.bpmn to zeebe broker failed 

### ISSUE THREAD

**Issue by pcouas** [berndruecker/flowing-retail#19]
Hi,

I have just started zeebe and i tried to add BPMN comming from project
C:\Users\windows\zeebe-distribution-0.17.0\zeebe-broker-0.17.0\bin\broker.bat OK
C:\Users\zeebe-distribution-0.17.0\zeebe-broker-0.17.0\bin\zbctl deploy C:\Users\tIdeaProjects\zeebejava\order\src\main\resources\order-zeebe.bpmn

15:40:33.721 [io.zeebe.gateway.impl.broker.cluster.BrokerTopologyManagerImpl] [gateway-zb-actors-0] INFO  io.zeebe.transport.endpoint - Registering endpoint for node '0' with address '0.0.0.0:26501' on transport 'broker-client-internal'
juin 07, 2019 3:40:57 PM io.grpc.netty.NettyServerTransport notifyTerminated
INFOS: Transport failed
java.io.IOException: Une connexion existante a d¹ Ûtre fermÚe par lÆh¶te distant
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
I use java8 

Regards

**Comment by berndruecker** [comment]
Can you retry things with 0.18?

Can you also try `zbctl status` to double check the connection to the broker is working correctly?

See also https://docs.zeebe.io/introduction/quickstart.html#step-2-start-the-zeebe-broker

Please re-open if you still face this issue - but a better place to get faster responses might be the Zeebe Forum or Slack channel: http://forum.zeebe.io/
