### ISSUE TITLE
Error When starting Order and Payement 

### ISSUE THREAD

**Issue by ccristian** [berndruecker/flowing-retail#5]
Noticed an error while starting thw two apps (individually they work)

Might be some shared lock on files ? same db ? 

org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-196])
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)

**Comment by ccristian** [comment]
seems like is that 

Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/cristianchiovari/Work/Projects/flowing-retail/camunda-db.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)

**Comment by berndruecker** [comment]
yeah - ideed. All services startup an own H2 database instance with a default file format located in the "current" directory. So if you start the mvn exec:java command from different directories it should work fine - if from the same they interfer. I will add some config to have different file names for the H2 databases to get rid of this. Thanks for reporting

**Comment by ccristian** [comment]
Thanks for response ...
